[package]
name = "popshot"
version = "1.0.0"
edition = "2024"
license = "MPL-2.0"
description = "Screenshot utility for CosmicDE."
repository = "https://github.com/ThunderGod95/popshot"

[dependencies]
i18n-embed = { version = "0.16", features = [
    "fluent-system",
    "desktop-requester",
] }
i18n-embed-fl = "0.10"
rust-embed = "8.8.0"
tokio = { version = "1.48.0", features = ["full"] }
ashpd = { version = "0.13.13", default-features = false, features = ["tokio", "notification", "screenshot", "file_chooser"] }
url = "2"
image = { version = "0.25", default-features = false, features = ["png"] }
wayland-client = "0.31.15"
zbus = { version = "5.19", default-features = false, features = ["tokio"] }
uuid = { version = "1", features = ["v4"] }
rustix = { version = "1", features = ["fs", "process"] }

[build-dependencies]
xdgen = "0.1"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
features = [
    "wgpu",
]

[profile.release]
lto = false
